public class MathematicalClass {
    public Integer addition(integer x, integer y) {
        integer sum = x+y;
        return sum;
    }

    public Integer subtraction(integer x, integer y) {
        integer result = x-y;
        return result;
    }

    public Integer multiplication(Integer x, integer y){
        Integer product = x*y;
        return product;
    }

    public Integer division(integer x, integer y){
        integer divResult = x/y;
        return divResult;
    }
}