// AccConAndOppOperations.fetchAllAccount2('Web', 'Closed won');
// AccConAndOppOperations.annRev('Engin', 20000000, 'Other');
// AccConAndOppOperations.allClosedWonSum();
// AccConAndOppOperations.listAccWithOpp('prospecting');
// AccConAndOppOperations.AccountList('Closed Won');
// AccConAndOppOperations.allClosedWonSum();
// AccConAndOppOperations.contactCreation('0018c00002JJQCLAA5');
// AccConAndOppOperations.updateOpp();
AccConAndOppOperations.OppsAccRelatedCreation(2,'0018c00002Ewf89AAB' );
