// AssignmentOwnTraining.sumOfAllClosedWonOpp();
// AssignmentOwnTraining.accountsWithOpps('Closed Won');
// AssignmentOwnTraining.accountsWithContacts();
// AssignmentOwnTraining.createContactWithAccId('0018c00002Ewf89AAB');
// AssignmentOwnTraining.updateDesc();
// AssignmentOwnTraining.nNumberOppForAcc(4, '0018c00002JJQC6AAP');
// AssignmentOwnTraining.noContactAcc();
AssignmentOwnTraining.oppDelete();
