// OperationsHelper op = new OperationsHelper();
// System.debug(op.largestOutOfTwoNumbers(10.4, 3.5));
// System.debug(op.smallestOutOfThreeNumbers(1.5, 0.9, 0.25));

// List<Decimal> Value = new List<decimal>{5,9,4,7};
// OperationsHelper.Average(Value);

// List<Decimal> Value = new List<decimal>{5,9,4,7,2};
// OperationsHelper.reverseListMethod(Value);

OperationsHelper op1 = new OperationsHelper();
op1.largestOutOfTwoNumbers(2.1, 4.5);
System.debug(op1.largestOutOfTwoNumbers(2.1, 4.5));
