/*StringDemoClass checklength = new StringDemoClass();
checklength.stringMethod1();*/

// StringDemoClass datecheck = new StringDemoClass();
// datecheck.printNewDate();

// StringDemoClass checksubs = new StringDemoClass();
// checksubs.printSubsEndDate();

// StringDemoClass checkoffer = new StringDemoClass();
// checkoffer.printDateTime();

StringDemoClass testcheck = new StringDemoClass();
testcheck.printteststrings();